version: '3.8'
services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql-cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersystem
      MYSQL_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/usersystem?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
