version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cont
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: userinfoapp
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  db_data:
