version: '3.8'
 
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cont2
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network
    restart: on-failure
 
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO
      - SPRING_JPA_SHOW_SQL
    networks:
      - my_network
    depends_on:
      - mysql
    restart: on-failure
 
volumes:
  mysql-data: {}
 
networks:
  my_network: {}
 